ApiMatchJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('company/', include(('company.urls', 'company'), namespace='company')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from home import views


urlpatterns = [
    path(
        route='',
        view=views.HomePage.as_view(),
        name='HomePage'
    ),
    path(
        route='login/',
        view=views.home_login,
        name='login'
    ),
    path(
        route='logout/',
        view=views.home_logout,
        name='logout'
    ),
    path(
        route='signup/',
        view=views.signup,
        name='signup'
    ),
    path(
        route='signup_company/',
        view=views.signup_company,
        name='signup_company'
    ),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
# django
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.models import User

# Exception
from django.db.utils import IntegrityError

# Models
from users.models import Profile as UserProfile
from company.models import ProfileCompany


def home_login(request):
    """Login view."""
    if request.user.is_authenticated:
        if UserProfile.objects.filter(user=request.user.id).exists():
            return HttpResponseRedirect(reverse('users:UsersHomePage'))
        elif ProfileCompany.objects.filter(user=request.user.id).exists():
            return HttpResponseRedirect(reverse('company:CompanyHomePage'))
        else:
            return HttpResponseRedirect(reverse('users:UsersHomePage'))

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if UserProfile.objects.filter(user=user).exists():
                return HttpResponseRedirect(reverse('users:UsersHomePage'))
            elif ProfileCompany.objects.filter(user=user).exists():
                return HttpResponseRedirect(reverse('company:CompanyHomePage'))
            else:
                return HttpResponseRedirect(reverse('users:UsersHomePage'))

        else:
            return render(request, 'home/login.html', {'error': 'Invalid username and password'})
    else:
        return render(request, 'home/login.html')


class HomePage(TemplateView):
    """Pagina Principal"""
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        """ get context """
        args = dict()
        return args


def home_logout(request):
    """logout """
    logout(request)
    return HttpResponseRedirect(reverse('home:login'))


def signup(request):
    """logout """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        cedula = request.POST['cedula']

        if password != password_confirmation:
            return render(request, 'home/signup.html', {'error': 'Password confirmation does not match'})

        if User.objects.filter(email=email).exists():
            return render(request, 'home/signup.html', {'error': 'Email is already in use'})

        if UserProfile.objects.filter(cedula=cedula).exists():
            return render(request, 'home/signup.html', {'error': 'Cedula is already in use'})

        try:
            user = User.objects.create_user(username=username, password=password)
        except IntegrityError:
            return render(request, 'home/signup.html', {'error': 'Username is already in use'})

        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()

        profile = UserProfile(user=user, cedula=cedula)
        profile.save()

        return HttpResponseRedirect(reverse('home:login'))
    return render(request, 'home/signup.html')


def signup_company(request):
    """logout """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        comercial_name = request.POST['comercial_name']
        email = request.POST['email']
        cedula = request.POST['cedula']

        if password != password_confirmation:
            return render(request, 'home/signup_company.html', {'error': 'Password confirmation does not match'})

        if User.objects.filter(email=email).exists():
            return render(request, 'home/signup_company.html', {'error': 'Email is already in use'})

        if UserProfile.objects.filter(cedula=cedula).exists():
            return render(request, 'home/signup_company.html', {'error': 'Cedula is already in use'})

        try:
            user = User.objects.create_user(username=username, password=password)
        except IntegrityError:
            return render(request, 'home/signup_company.html', {'error': 'Username is already in use'})

        user.first_name = ""
        user.last_name = ""
        user.email = email
        user.save()

        profile = ProfileCompany(user=user, cedula=cedula, comercial_name=comercial_name)
        profile.save()

        return HttpResponseRedirect(reverse('home:login'))
    return render(request, 'home/signup_company.html')

templates/home/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

    <title>MJ | Login</title>
  </head>
  <body style="background-size: cover; backdrop-filter: grayscale(.7); position: absolute; top:0; bottom: 0; left: 0; right: 0; 
        background-color: rgba(0,0,0,0.5); z-index: 1;"  background="{% static 'images/tech_program.jpeg' %}"  >
    <section class=" text-white" style="height: 100vh;">
        <div class="container-fluid h-custom ">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img src="{% static 'images/logo_match_job_blanco.png' %}" class="" width="100%" height="auto" />
            </div>
            <div-- class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 text-center">
              <form method="POST">
              {% csrf_token %}

                <div class="divider d-flex align-items-center my-4 text-center">
                  <H1 class="text-center fw-bold mx-3 mb-0 "><span style="color: #7c9afb;">BIENV</span> <span style="color: #92fc69; margin-left: -10px;">ENIDO</span></H1>
                </div>

                {% if error %}
                <div>
                  <p class="alert alert-danger">{{ error }}</p>
                </div>
                {% endif %}
                <div class="form-outline mb-2">
                  <input type="text" id="username" class="form-control form-control-lg"
                         placeholder="Username"  name="username" />
                </div>
      

                <div class="form-outline mb-2">
                  <input type="password" id="password" class="form-control form-control-lg"
                         placeholder="Enter password"  name="password" />
                </div>
      
                <!--div class="d-flex justify-content-between align-items-center">
                  <div class="form-check mb-0">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                    <label class="form-check-label" for="form2Example3">
                      Remember me
                    </label>
                  </div>
                  <a href="#!" class="text-body">Forgot password?</a>
                </div-->
      
                <div class="text-center text-lg-start mt-4 pt-2">
                  <button type="submit" class="btn bg-mj-a btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'home:signup' %}"
                      class="text-mja">Register</a></p>
                  <p class="small fw-bold mt-2 pt-1 mb-0"><a href="{% url 'home:HomePage' %}"
                    class="text-danger">Regresar</a></p>
                </div>
      
              </form>
            </div>
          </div>
        </div>
        
    </section>
      <div></div>
      <div class="container-fluid">
          <div class="row position-sticky-bottom">
              <div class="col-12 py-4 px-4 px-xl-5 bg-mj-a text-center">
                <div class="text-white mb-3 mb-md-0">
                    Copyright © 2020. All rights reserved.
                </div>
              </div>
          </div>
      </div>

      
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

  </body>
</html>

templates/home/signup.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

    <title>MJ | Login</title>
  </head>
  <body>
    <section class="bg-dark text-white" style="height: 100vh;">
        <div class="container-fluid h-custom bg-dark">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img src="{% static 'images/logo_match_job_blanco.png' %}" class="" width="100%" height="auto" />
            </div>
            <div-- class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 text-center">
              <form method="POST" action="{%  url 'home:signup' %}">
              {% csrf_token %}
                <div class="divider d-flex align-items-center my-4">
                    <H1 class="text-center fw-bold mx-3 mb-0 "><span style="color: #7c9afb;">REGI</span> <span style="color: #92fc69; margin-left: -10px;">STRO</span></H1>
                </div>

                {% if error %}
                <div>
                  <p class="alert alert-danger">{{ error }}</p>
                </div>
                {% endif %}

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="Username" id="username" name="username" required="true" />                    
                    </div>                       
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="password" placeholder="Password" id="password" name="password" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="password" placeholder="Password confirmation" id="password_confirmation" name="password_confirmation" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="First name" id="first_name" name="first_name" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="Last name" id="last_name" name="last_name" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="cedula" id="cedula" name="cedula" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="email" placeholder="Email" id="email" name="email" required="true" />        
                    </div>                                                  
                </div>

                <div class="row mb-2">
                    <div class="col-11 offset-1 align-self-start text-start ">
                        <a href="#!" class="text-white text-start">Términos y Condiciones Generales</a>
                    </div>
                    <div class="col-11 offset-1 align-self-start text-start">
                        <a href="#!" class="text-white">Políticas de Privacidad</a>
                    </div>
                </div>

                
                <div class="row">
                    <div class="col-11 offset-1 align-self-start text-start">
                        <input class="form-check-input" type="checkbox" value="" id="conditions" name="conditions" required />
                        <label class="form-check-label" for="conditions">
                            Acepto los términos y condiciones
                        </label>
                    </div>                    
                </div>
                
                <div class="row">
                    <div class="col-11 offset-1 align-self-start text-start">
                        <div class="text-center text-lg-start mt-2 pt-2 mb-5 pb-5">
                            <button type="submit" class="btn bg-mj-a btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Registrarte</button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">¿Ya tienes una cuenta? <a href="{% url 'home:login' %}"
                                class="text-mja">Ingresa</a></p>
                            <p class="small fw-bold mt-2 pt-1 mb-0"><a href="{% url 'home:HomePage' %}"
                                class="text-danger">Regresar</a></p>
                        </div>
                    </div>
                </div>
                

      
              </form>
            </div>
          </div>
        </div>
        
      </section>


      
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

  </body>
</html>

templates/home/signup_company.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

    <title>MJ | Login</title>
  </head>
  <body>
    <section class="bg-dark text-white" style="height: 100vh;">
        <div class="container-fluid h-custom bg-dark">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img src="{% static 'images/logo_match_job_blanco.png' %}" class="" width="100%" height="auto" />
            </div>
            <div-- class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 text-center">
              <form method="POST" action="{%  url 'home:signup_company' %}">
              {% csrf_token %}
                <div class="divider d-flex align-items-center my-4">
                    <H1 class="text-center fw-bold mx-3 mb-0 "><span style="color: #7c9afb;">REGI</span> <span style="color: #92fc69; margin-left: -10px;">STRO</span></H1>
                </div>

                {% if error %}
                <div>
                  <p class="alert alert-danger">{{ error }}</p>
                </div>
                {% endif %}

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="Username" id="username" name="username" required="true" />                    
                    </div>                       
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="password" placeholder="Password" id="password" name="password" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="password" placeholder="Password confirmation" id="password_confirmation" name="password_confirmation" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="Nombre Comercial" id="comercial_name" name="comercial_name" required="true" />                    
                    </div>                       
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="text" placeholder="cedula" id="cedula" name="cedula" required="true" />                    
                    </div>   
                    
                </div>

                <div class="row mb-2">
                    <label for="email" class="col-1 col-form-label">
                        <img src="{% static 'images/icons/information.png' %}" class="rounded-circle" width="25px" height="auto" />
                    </label>
                    <div class="col-11">
                        <input class="form-control form-control-lg" type="email" placeholder="Email" id="email" name="email" required="true" />        
                    </div>                                                  
                </div>

                <div class="row mb-2">
                    <div class="col-11 offset-1 align-self-start text-start ">
                        <a href="#!" class="text-white text-start">Términos y Condiciones Generales</a>
                    </div>
                    <div class="col-11 offset-1 align-self-start text-start">
                        <a href="#!" class="text-white">Políticas de Privacidad</a>
                    </div>
                </div>

                
                <div class="row">
                    <div class="col-11 offset-1 align-self-start text-start">
                        <input class="form-check-input" type="checkbox" value="" id="conditions" name="conditions" required />
                        <label class="form-check-label" for="conditions">
                            Acepto los términos y condiciones
                        </label>
                    </div>                    
                </div>
                
                <div class="row">
                    <div class="col-11 offset-1 align-self-start text-start">
                        <div class="text-center text-lg-start mt-2 pt-2 mb-5 pb-5">
                            <button type="submit" class="btn bg-mj-a btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Registrarte</button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">¿Ya tienes una cuenta? <a href="{% url 'home:login' %}"
                                class="text-mja">Ingresa</a></p>
                            <p class="small fw-bold mt-2 pt-1 mb-0"><a href="{% url 'home:HomePage' %}"
                                class="text-danger">Regresar</a></p>
                        </div>
                    </div>
                </div>
                

      
              </form>
            </div>
          </div>
        </div>
        
      </section>


      
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

  </body>
</html>