ApiMatchJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('company/', include(('company.urls', 'company'), namespace='company')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from company import views


urlpatterns = [

    # Management
    path(
        route='CompanyHomePage',
        view=views.CompanyHomePage.as_view(),
        name='CompanyHomePage'
    ),
    path(
        route='CompanyPerfilPage',
        view=views.company_perfil_page,
        name='CompanyPerfilPage'
    ),
    path(
        route='CompanyNMPage',
        view=views.company_new_match_page,
        name='CompanyNMPage'
    ),
    path(
        route='CompanyMatchPage',
        view=views.CompanyMatchPage.as_view(),
        name='CompanyMatchPage'
    ),
    path(
        route='CompanyMatchPageAceptados',
        view=views.CompanyMatchPageAceptados.as_view(),
        name='CompanyMatchPageAceptados'
    ),
    path(
        route='CompanyMatchPageDeclinados',
        view=views.CompanyMatchPageDeclinados.as_view(),
        name='CompanyMatchPageDeclinados'
    ),
    path(
        route='CompanyMatchPageRechazados',
        view=views.CompanyMatchPageRechazados.as_view(),
        name='CompanyMatchPageRechazados'
    ),


]

home/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from home import views


urlpatterns = [
    path(
        route='',
        view=views.HomePage.as_view(),
        name='HomePage'
    ),
    path(
        route='login/',
        view=views.home_login,
        name='login'
    ),
    path(
        route='logout/',
        view=views.home_logout,
        name='logout'
    ),
    path(
        route='signup/',
        view=views.signup,
        name='signup'
    ),
    path(
        route='signup_company/',
        view=views.signup_company,
        name='signup_company'
    ),
]

company/models.py
# Django
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Country

# Create your models here.

# Empresa


class SubscriptionCompany(models.Model):
    """Planes de pago"""
    name = models.CharField(max_length=500)
    description = models.TextField(default="")
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % (self.name)


class ProfileCompany(models.Model):
    """Perfil de la empresa"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comercial_name = models.CharField(max_length=150,  blank=True, null=True)
    picture = models.ImageField(upload_to='Company/pictures', blank=True, null=True)
    phone_number = models.CharField(default=" ", max_length=20, blank=True, null=True)
    web_site = models.URLField(default=" ", blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    lon = models.FloatField(blank=True, null=True)
    cedula = models.CharField(max_length=50, unique=True)
    biography = models.TextField(blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING, blank=True, null=True)
    subscription = models.ForeignKey(SubscriptionCompany, on_delete=models.DO_NOTHING, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % self.user.username

company/forms.py
"""User forms."""

# Django
from django import forms


class CompanyProfileForm(forms.Form):
    """Profile form."""

    picture = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    web_site = forms.URLField(required=False)
    lat = forms.FloatField(required=False)
    lon = forms.FloatField(required=False)
    biography = forms.CharField(max_length=500, required=False)

company/views.py
# django
from django.views.generic import TemplateView
from django.shortcuts import render

# Django Rest Framework

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated

# frameworks
from frameworks.frameworks import get_data_combos_profile, get_url_zone

# models
from profiles.models import *
from .models import ProfileCompany

# forms
from .forms import CompanyProfileForm

# Create your views here.


class CompanyHomePage(TemplateView):
    """Pagina Principal"""
    template_name = "company/home_company.html"

    def get_context_data(self, **kwargs):
        """ Obtiene datos del perfil"""
        menu_dict = dict()
        return menu_dict


def company_perfil_page(request):
    """Pagina Principal"""

    if request.method == "POST":
        profile = request.user.profilecompany
        form = CompanyProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            profile.phone_number = data['phone_number']
            profile.web_site = data['web_site']
            profile.lat = data['lat']
            profile.lon = data['lon']
            profile.biography = data['biography']
            if data['picture']:
                profile.picture = data['picture']
            profile.save()

        dict_perfil = get_data_combos_profile(request.user.id)
        dict_perfil['map'] = get_url_zone(request.user.profilecompany.lat, request.user.profilecompany.lon)
        dict_perfil['form'] = form
        return render(request, 'company/company_perfil.html', dict_perfil)

    dict_perfil = get_data_combos_profile(request.user.id)
    dict_perfil['map'] = get_url_zone(request.user.profilecompany.lat, request.user.profilecompany.lon)
    form = CompanyProfileForm()
    dict_perfil['form'] = form
    return render(request, 'company/company_perfil.html', dict_perfil)


def company_new_match_page(request):
    """Pagina Principal"""
    if request.method == "POST":
        dict_perfil = get_data_combos_profile(request.user.id)
        dict_perfil['busqueda_realizada'] = 1
        return render(request, 'company/company_new_match.html', dict_perfil)
    else:
        dict_perfil = get_data_combos_profile(request.user.id)
        return render(request, 'company/company_new_match.html', dict_perfil)


class CompanyMatchPage(TemplateView):
    """Pagina Principal"""
    template_name = "company/company_match_realizados.html"

    def get_context_data(self, **kwargs):
        """ context """
        args = dict()
        return args


class CompanyMatchPageAceptados(TemplateView):
    """Pagina Principal"""
    template_name = "company/company_match_aceptados.html"

    def get_context_data(self, **kwargs):
        """ context """
        args = dict()
        return args


class CompanyMatchPageDeclinados(TemplateView):
    """Pagina Principal"""
    template_name = "company/company_match_declinados.html"

    def get_context_data(self, **kwargs):
        """ context """
        args = dict()
        return args


class CompanyMatchPageRechazados(TemplateView):
    """Pagina Principal"""
    template_name = "company/company_match_rechazados.html"

    def get_context_data(self, **kwargs):
        """ context """
        args = dict()
        return args

templates/company/company_match_aceptados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
    <a href="{% url 'company:CompanyMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'company:CompanyMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
 </div>
 <div class="col-3 mx-auto">
  <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
 </div>
 <div class="col-3 mx-auto ">
  <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
 </div>
 <div class="col-3 mx-auto">
  <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
 </div>
 </div>
<div class="row">
    
    <div class="col-12 col-md-4 mx-auto py-3">
        <div class="card mb-3" style="width:100%;">
            <div class="row">
              <div class="col-md-4 p-2 mx-auto text-center">
                <img src="{% static 'images/users/user_k.jpg' %}"  class="img-fluid rounded-start ">
                
              </div>
              <div class="col-md-8">
                <div class="card-body text-center">
                  <h5 class="card-title text-center bg-success text-white">{{ Nombre_Empresa }}Lena Marcos Ayala</h5>
                  <p class="card-text text-center">2019 - Actual</p>
                  <a href="#" >Mas sobre Lena Marcos Ayala</a>
                </div>
                <div class="card-footer text-muted">
                    
                    <div class="row">
                        <div class="col-12 mx-auto">
                            <p class="card-text"><small class="text-muted">Aceptado hace 2 años</small></p>
                        </div>                      
                    </div>
                  </div>
              </div>
            </div>
          </div>

    </div>
</div>

 {% endblock%}  

templates/company/company_match_declinados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
    <a href="{% url 'company:CompanyMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'company:CompanyMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
 </div>
 <div class="col-3 mx-auto">
  <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
 </div>
 <div class="col-3 mx-auto ">
  <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
 </div>
 <div class="col-3 mx-auto">
  <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
 </div>
 </div>
<div class="row">
    
    <div class="col-12 col-md-4 mx-auto py-3">
        <div class="card mb-3" style="width:100%;">
            <div class="row">
              <div class="col-md-4 p-2 mx-auto text-center">
                <img src="{% static 'images/users/user_l.jpg' %}"  class="img-fluid rounded-start ">
                
              </div>
              <div class="col-md-8">
                <div class="card-body text-center">
                  <h5 class="card-title text-center bg-warning">{{ Nombre_Empresa }}Ezio Pérez Santana</h5>
                  <p class="card-text text-center ">Declinado por la entrevista, no nos convencio su actitud</p>
                  <a href="#" >Mas sobre Ezio Pérez Santana</a>
                </div>
                <div class="card-footer text-muted">
                    
                    <div class="row">
                        <div class="col-12 mx-auto">
                            <p class="card-text"><small class="text-muted">Contactado hace 2 años</small></p>
                        </div>                      
                    </div>
                  </div>
              </div>
            </div>
          </div>

    </div>
</div>


 {% endblock%}  

templates/company/company_match_realizados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
      <a href="{% url 'company:CompanyMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
      <a href="{% url 'company:CompanyMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto ">
    <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
   </div>
 </div>
<div class="row">
  <div class="col-12 col-md-12">
    <div class="row">
      <div class="col-12 text-mja text-center mb-3">
    

      </div>
    </div>
    <div class="row">

      <div class="col-12 col-md-4 mx-auto">
        <div class="card mb-3" style="width:100%;">
          <div class="row">
            <div class="col-md-4 p-2 mx-auto text-center">
              <img src="{% static 'images/users/user_i.jpg' %}"  class="img-fluid rounded-start ">
              <a href="#" >Mas sobre Denis Mata Gamez</a>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title text-center">{{ Nombre_Empresa }}Denis Mata Gamez</h5>
                <p class="card-text bg-warning text-dark">Pendiente de Respuesta</p>
                <h6>Entrevista</h6>
                <li>Cita: 9am</li>
                <br>         
                <p>Descripcion: Desarrollo de front end </p>
                                

                <div class="row">
                  <div class="col-4 mx-auto">
                      <a href="#" class="btn btn-success btn-sm"  data-bs-toggle="modal" data-bs-target="#ModalAceptar">Contratado</a>
                    </div>  
                  <div class="col-4 mx-auto">
                    <a href="#" class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#ModalRechazar">Declinar</a>
                  </div>                      
              </div>
                
                
              </div>
              <div class="card-footer text-muted">
                  
                  <div class="row">
                      <div class="col-12 mx-auto">
                          <p class="card-text"><small class="text-muted">Match realizado hace 15 minutos</small></p>
                        </div>                      
                  </div>
                </div>
            </div>
          </div>
      </div>
      </div>

      <div class="col-12 col-md-4 mx-auto">
        <div class="card mb-3" style="width:100%;">
          <div class="row">
            <div class="col-md-4 p-2 mx-auto text-center">
              <img src="{% static 'images/users/user_j.jpg' %}"  class="img-fluid rounded-start ">
              <a href="#" >Mas sobre Rainer Candelaria Patino</a>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title text-center">{{ Nombre_Empresa }}Rainer Candelaria Patino</h5>
                <p class="card-text bg-success text-white">Entrevista Confirmada</p>
                <h6>Entrevista</h6>
                <li>Cita: 10am</li>
                <br>         
                <p>Descripcion: Desarrollo de front end </p>
                                

                <div class="row">
                  <div class="col-4 mx-auto">
                      <a href="#" class="btn btn-success btn-sm"  data-bs-toggle="modal" data-bs-target="#ModalAceptar">Contratado</a>
                    </div>  
                  <div class="col-4 mx-auto">
                    <a href="#" class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#ModalRechazar">Declinar</a>
                  </div>                      
              </div>
                
                
              </div>
              <div class="card-footer text-muted">
                  
                  <div class="row">
                      <div class="col-12 mx-auto">
                          <p class="card-text"><small class="text-muted">Match realizado hace 15 minutos</small></p>
                        </div>                      
                  </div>
                </div>
            </div>
          </div>
      </div>
      </div>


    </div>
  </div>
</div>

<!-- Modal Aceptar-->
<div class="modal fade" id="ModalAceptar" tabindex="-1" aria-labelledby="ModalAceptarLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalAceptarLabel">Match Aceptado</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>¡Felicidades! usted ha seleccionado a su candidato</p>           
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal Rechazar-->
<div class="modal fade" id="ModalRechazar" tabindex="-1" aria-labelledby="ModalRechazarLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalRechazarLabel">Match Declinado</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label">¿Porque declino el match?</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
            </div>
          </form>          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="button" class="btn btn-warning">Declino el Match</button>
        </div>
      </div>
    </div>
  </div>

 {% endblock%}  

templates/company/company_match_rechazados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
    <a href="{% url 'company:CompanyMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'company:CompanyMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
 </div>
 <div class="col-3 mx-auto">
  <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
 </div>
 <div class="col-3 mx-auto ">
  <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
 </div>
 <div class="col-3 mx-auto">
  <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
  <a href="{% url 'company:CompanyMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
 </div>
 </div>
<div class="row">
    
    <div class="col-12 col-md-4 mx-auto py-3">
        <div class="card mb-3" style="width:100%;">
            <div class="row">
              <div class="col-md-4 p-2 mx-auto text-center">
                <img src="{% static 'images/users/user_m.jpg' %}"  class="img-fluid rounded-start ">
                
              </div>
              <div class="col-md-8">
                <div class="card-body text-center">
                  <h5 class="card-title text-center bg-danger text-white">{{ Nombre_Empresa }}Herón Abreu Anaya</h5>
                  <p class="card-text text-center">Rechazaron tu match porque: El salario es mas bajo de lo que estoy buscando</p>
                  <a href="#" >Mas sobre Herón Abreu Anaya</a>
                </div>
                <div class="row justify-content-end text-end">
                  <div class="col-12 align-self-end offset-6">
                    
                  </div>                      
                </div>
                <div class="card-footer text-muted">
                    
                    <div class="row">
                        <div class="col-12 mx-auto">
                            <p class="card-text"><small class="text-muted">Postulado hace 2 años</small></p>
                        </div>                      
                    </div>
                  </div>
              </div>
            </div>
          </div>

    </div>
</div>
<!-- Modal Aceptar-->
<div class="modal fade" id="ModalAceptar" tabindex="-1" aria-labelledby="ModalAceptarLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalAceptarLabel">¿Como conseguir puestos similares?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <h6>Para conseguir este puesto o similares a este te sugerimos tomar los siguientes cursos:</h6>  
          <li><a href="https://platzi.com/clases/assets-3d/" target="_blank" >Platzi: Curso de Assets 3D para Videojuegos</a></li>
          <li><a href="https://platzi.com/clases/animacion-videojuegos/" target="_blank">Platzi:  Animación y Arte de Videojuegos 2D</a></li>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
 {% endblock%}  

templates/company/home_company.html
{% extends 'users/base.html' %}
{% block title %} <span style="color: #7c9afb;">Bienvenido</span> <span style="color: #92fc69;">{{ user.username | title }}</span>    {% endblock%}   
{% block container %}
<div class="row">
    <div class="col-11 mx-auto">
       <div class="card my-2">

           <div class="card-body text-end">
             <blockquote class="blockquote mb-0">
               <p>Una gran visión sin grandes personas es irrelevante</p>
               <footer class="blockquote-footer"><cite title="Source Title">Jim Collins</cite></footer>
             </blockquote>
           </div>
         </div>
    </div>
</div>

<div class="row my-2">
   <div class="col-12 col-lg-3 mx-auto my-2">
       <div class="card" style="width: 100%;">
           <div class="card-body">
             <h4 class="card-title">Match Pendientes</h4>
             <h5 class="card-subtitle mb-2 text-muted">Match Pendientes: <span class="text-success fw-bold "> 1 </span> </h5>
             <p class="card-text">Aqui puedes ver como van los candidatos con los que has hecho match</p>
           </div>
       </div>
       <div class="card-footer text-end bg-mj-v ">
           <a  href="{% url 'company:CompanyMatchPage' %}" class="card-link fw-bold">Ver Match</a>
       </div>
    </div>

    <div class="col-12 col-lg-3 mx-auto my-2">
       <div class="card" style="width: 100%;">
           <div class="card-body">
             <h4 class="card-title">Nueva Busqueda</h4>
             <h5 class="card-subtitle mb-2 text-muted">Busquedas realziadas: <span class="text-success fw-bold "> 1 </span> </h5>
             <p class="card-text">Aqui puedes Encontrar a tu candidato perfecto solo filtrando su perfil y/o habilidades</p>
           </div>
       </div>
       <div class="card-footer text-end bg-mj-v ">
           <a href="{% url 'company:CompanyNMPage' %}" class="card-link fw-bold">Buscar Candidatos</a>
       </div>
    </div>   
</div>


   

{% endblock%}  