ApiMatchJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('company/', include(('company.urls', 'company'), namespace='company')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from company import views


urlpatterns = [

    # Management
    path(
        route='CompanyHomePage',
        view=views.CompanyHomePage.as_view(),
        name='CompanyHomePage'
    ),
    path(
        route='CompanyPerfilPage',
        view=views.company_perfil_page,
        name='CompanyPerfilPage'
    ),
    path(
        route='CompanyNMPage',
        view=views.company_new_match_page,
        name='CompanyNMPage'
    ),
    path(
        route='CompanyMatchPage',
        view=views.CompanyMatchPage.as_view(),
        name='CompanyMatchPage'
    ),
    path(
        route='CompanyMatchPageAceptados',
        view=views.CompanyMatchPageAceptados.as_view(),
        name='CompanyMatchPageAceptados'
    ),
    path(
        route='CompanyMatchPageDeclinados',
        view=views.CompanyMatchPageDeclinados.as_view(),
        name='CompanyMatchPageDeclinados'
    ),
    path(
        route='CompanyMatchPageRechazados',
        view=views.CompanyMatchPageRechazados.as_view(),
        name='CompanyMatchPageRechazados'
    ),


]

home/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from home import views


urlpatterns = [
    path(
        route='',
        view=views.HomePage.as_view(),
        name='HomePage'
    ),
    path(
        route='login/',
        view=views.home_login,
        name='login'
    ),
    path(
        route='logout/',
        view=views.home_logout,
        name='logout'
    ),
    path(
        route='signup/',
        view=views.signup,
        name='signup'
    ),
    path(
        route='signup_company/',
        view=views.signup_company,
        name='signup_company'
    ),
]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from users import views


urlpatterns = [

    # Management
    path(
        route='UsersHomePage',
        view=views.UsersHomePage.as_view(),
        name='UsersHomePage'
    ),
    path(
        route='UsersPerfilPage',
        view=views.users_perfil_page,
        name='UsersPerfilPage'
    ),
    path(
        route='UsersHVPage',
        view=views.users_hoja_vida_page,
        name='UsersHVPage'
    ),
    path(
        route='UsersMatchPage',
        view=views.UsersMatchPage.as_view(),
        name='UsersMatchPage'
    ),
    path(
        route='UsersMatchPageAceptados',
        view=views.UsersMatchPageAceptados.as_view(),
        name='UsersMatchPageAceptados'
    ),
    path(
        route='UsersMatchPageDeclinados',
        view=views.UsersMatchPageDeclinados.as_view(),
        name='UsersMatchPageDeclinados'
    ),
    path(
        route='UsersMatchPageRechazados',
        view=views.UsersMatchPageRechazados.as_view(),
        name='UsersMatchPageRechazados'
    ),
    path(
        route='UsersTestPage',
        view=views.UsersTestPage.as_view(),
        name='UsersTestPage'
    ),
    path(
        route='UsersEvolutionPage',
        view=views.UsersEvolutionPage.as_view(),
        name='UsersEvolutionPage'
    ),
    path(
        route='add_skill',
        view=views.add_skill,
        name='add_skill'
    ),

    path(
        route='add_soft_skill',
        view=views.add_soft_skill,
        name='add_soft_skill'
    ),

    path(
        route='add_language',
        view=views.add_language,
        name='add_language'
    ),

]

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import User
from django.db import models
from profiles.models import Language, Department, Specialism, Skills, SoftSkill, Level, Country


class Profile(models.Model):
    """profile"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, blank=True, null=True)
    specialism = models.ForeignKey(Specialism, on_delete=models.DO_NOTHING, blank=True, null=True)
    skills = models.ManyToManyField(Skills, through='UserSkills', blank=True, null=True)
    soft_skills = models.ManyToManyField(SoftSkill, through='UserSoftSkills', blank=True, null=True)
    languages = models.ManyToManyField(Language, through='UserLanguages', blank=True, null=True)
    currently_working = models.BooleanField(default=False)
    search_job = models.BooleanField(default=True)
    home_office = models.BooleanField(default=False)
    freelancer = models.BooleanField(default=False)
    residence_change = models.BooleanField(default=False)
    remote_work = models.BooleanField(default=False)
    to_travel = models.BooleanField(default=False)
    desired_salary = models.IntegerField(default=0, blank=True, null=True)
    current_salary = models.IntegerField(default=0, blank=True, null=True)
    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)
    phone_number = models.CharField(default=" ", max_length=20, blank=True, null=True)
    web_site = models.URLField(default=" ", blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    lon = models.FloatField(blank=True, null=True)
    cedula = models.CharField(max_length=50, unique=True)
    biography = models.TextField(blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING, blank=True, null=True)
    nearby_search = models.BooleanField(default=True)
    gender = models.CharField(default=" ", max_length=50)
    academic_title = models.CharField(default=" ", max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % self.user.username


class UserSkills(models.Model):
    """UserSkills"""
    skill = models.ForeignKey(Skills, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s : %s - %s' % (self.profile.user.username, self.skill.name, self.level.description)


class UserSoftSkills(models.Model):
    """UserSoftSkills"""
    SoftSkill = models.ForeignKey(SoftSkill, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s : %s - %s' % (self.profile.user.username, self.SoftSkill.name, self.level.description)


class UserLanguages(models.Model):
    """UserSoftSkills"""
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s : %s - %s' % (self.profile.user.username, self.language.name, self.level.description)

users/forms.py
"""User forms."""

# Django
from django import forms
from profiles.models import Language, Department, Specialism, Skills, SoftSkill, Level, Country
from users.models import Profile


class ProfileForm(forms.Form):
    """Profile form."""

    department = forms. ModelChoiceField(queryset=Department.objects.values().filter(), label='departament' )
    specialism = forms.ModelChoiceField(queryset=Specialism.objects.values().filter(), label='specialism')
    currently_working = forms.BooleanField(required=False)
    search_job = forms.BooleanField(required=False)
    home_office = forms.BooleanField(required=False)
    freelancer = forms.BooleanField(required=False)
    residence_change = forms.BooleanField(required=False)
    remote_work = forms.BooleanField(required=False)
    to_travel = forms.BooleanField(required=False)
    desired_salary = forms.IntegerField(required=False)
    current_salary = forms.IntegerField(required=False)
    picture = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    web_site = forms.URLField(required=False)
    lat = forms.FloatField(required=False)
    lon = forms.FloatField(required=False)
    biography = forms.CharField(max_length=500, required=False)
    country = forms.ModelChoiceField(queryset=Country.objects.values().filter(), label='country')
    nearby_search = forms.BooleanField(required=False)
    gender = forms.CharField(max_length=50, required=False)
    academic_title = forms.CharField(max_length=50, required=False)

home/views.py
# django
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.models import User

# Exception
from django.db.utils import IntegrityError

# Models
from users.models import Profile as UserProfile
from company.models import ProfileCompany


def home_login(request):
    """Login view."""
    if request.user.is_authenticated:
        if UserProfile.objects.filter(user=request.user.id).exists():
            return HttpResponseRedirect(reverse('users:UsersHomePage'))
        elif ProfileCompany.objects.filter(user=request.user.id).exists():
            return HttpResponseRedirect(reverse('company:CompanyHomePage'))
        else:
            return HttpResponseRedirect(reverse('users:UsersHomePage'))

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if UserProfile.objects.filter(user=user).exists():
                return HttpResponseRedirect(reverse('users:UsersHomePage'))
            elif ProfileCompany.objects.filter(user=user).exists():
                return HttpResponseRedirect(reverse('company:CompanyHomePage'))
            else:
                return HttpResponseRedirect(reverse('users:UsersHomePage'))

        else:
            return render(request, 'home/login.html', {'error': 'Invalid username and password'})
    else:
        return render(request, 'home/login.html')


class HomePage(TemplateView):
    """Pagina Principal"""
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        """ get context """
        args = dict()
        return args


def home_logout(request):
    """logout """
    logout(request)
    return HttpResponseRedirect(reverse('home:login'))


def signup(request):
    """logout """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        cedula = request.POST['cedula']

        if password != password_confirmation:
            return render(request, 'home/signup.html', {'error': 'Password confirmation does not match'})

        if User.objects.filter(email=email).exists():
            return render(request, 'home/signup.html', {'error': 'Email is already in use'})

        if UserProfile.objects.filter(cedula=cedula).exists():
            return render(request, 'home/signup.html', {'error': 'Cedula is already in use'})

        try:
            user = User.objects.create_user(username=username, password=password)
        except IntegrityError:
            return render(request, 'home/signup.html', {'error': 'Username is already in use'})

        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()

        profile = UserProfile(user=user, cedula=cedula)
        profile.save()

        return HttpResponseRedirect(reverse('home:login'))
    return render(request, 'home/signup.html')


def signup_company(request):
    """logout """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        comercial_name = request.POST['comercial_name']
        email = request.POST['email']
        cedula = request.POST['cedula']

        if password != password_confirmation:
            return render(request, 'home/signup_company.html', {'error': 'Password confirmation does not match'})

        if User.objects.filter(email=email).exists():
            return render(request, 'home/signup_company.html', {'error': 'Email is already in use'})

        if UserProfile.objects.filter(cedula=cedula).exists():
            return render(request, 'home/signup_company.html', {'error': 'Cedula is already in use'})

        try:
            user = User.objects.create_user(username=username, password=password)
        except IntegrityError:
            return render(request, 'home/signup_company.html', {'error': 'Username is already in use'})

        user.first_name = ""
        user.last_name = ""
        user.email = email
        user.save()

        profile = ProfileCompany(user=user, cedula=cedula, comercial_name=comercial_name)
        profile.save()

        return HttpResponseRedirect(reverse('home:login'))
    return render(request, 'home/signup_company.html')

templates/users/crecimientos.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Creci</span> <span style="color: #92fc69; margin-left: -10px;">miento</span> {% endblock%}   
 {% block container %}
<div class="row">
    <div class="col-6 mx-auto py-3">
      <div class="card">
        <div class="card-header">
          <h3>Tu perfil: Front End</h3> 
        </div>
        <div class="card-body">
          <h5 class="card-title">Habilidades para reforzar tu perfil</h5>

          <li class="card-text">Django: Avanzado </li>
          <li class="card-text">HTML: Basico </li>

          <div class="row justify-content-end text-end">
            <div class="col-12 align-self-end offset-6">
              <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ModalAceptar">¿Como superarme?</a>
            </div>                      
          </div>

        </div>
      </div>
    </div>
</div>

<!-- Modal Aceptar-->
<div class="modal fade" id="ModalAceptar" tabindex="-1" aria-labelledby="ModalAceptarLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalAceptarLabel">¿Como Superarme?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <h6>Para superarte puedes tomar los siguientes cursos:</h6>  
            <li><a href="https://platzi.com/clases/html-css/" target="_blank" >Platzi: Clases del Curso Definitivo de HTML y CSS</a></li>
            <li><a href="https://platzi.com/clases/html-css/" target="_blank">Platzi: Curso Avanzado de Django</a></li>
            
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>



 {% endblock%}  

templates/users/home.html
 {% extends 'users/base.html' %}
 {% block title %} <span style="color: #7c9afb;">Bienvenido</span> <span style="color: #92fc69;">{{ user.username | title }}</span>    {% endblock%}   
 {% block container %}
 <div class="row">
     <div class="col-11 mx-auto">
        <div class="card my-2">

            <div class="card-body text-end">
              <blockquote class="blockquote mb-0">
                <p>Una gran visión sin grandes personas es irrelevante</p>
                <footer class="blockquote-footer"><cite title="Source Title">Jim Collins</cite></footer>
              </blockquote>
            </div>
          </div>
     </div>
 </div>

 <div class="row my-2">
    <div class="col-12 col-lg-3 mx-auto my-2">
        <div class="card" style="width: 100%;">
            <div class="card-body">
              <h4 class="card-title">Match Realizados</h4>
              <h5 class="card-subtitle mb-2 text-muted">Match Pendientes: <span class="text-success fw-bold "> 1 </span> </h5>
              <p class="card-text">Ve quien te realiza match y porque no te han aceptado</p>
            </div>
        </div>
        <div class="card-footer text-end bg-mj-v ">
            <a  href="{% url 'users:UsersMatchPage' %}" class="card-link fw-bold">Ver Match</a>
        </div>
     </div>

     <div class="col-12 col-lg-3 mx-auto my-2">
        <div class="card" style="width: 100%;">
            <div class="card-body">
              <h4 class="card-title">Hoja de Vida</h4>
              <h5 class="card-subtitle mb-2 text-muted">Salud del Pefil: <span class="text-success fw-bold "> Excelente </span> </h5>
              <p class="card-text">Manten tu perfil actualizado constantemente</p>
            </div>
        </div>
        <div class="card-footer text-end bg-mj-v ">
            <a href="{% url 'users:UsersHVPage' %}" class="card-link fw-bold">Actualizar Hoja de vida</a>
        </div>
     </div>
     
     <div class="col-12 col-lg-8 mx-auto my-2">
      <div class="card" style="width: 100%;">
          <div class="card-body">
            <h4 class="card-title">¿Que te hace falta?</h4>
            <p class="card-text">Seleccionaste Front End como tu terfil preferido, hemos detectado que hay áreas en las que puedes crecer.</p>
          </div>
      </div>
      <div class="card-footer text-end bg-mj-v ">
          <a href="{% url 'users:UsersEvolutionPage' %}" class="card-link fw-bold">Ver mi crecimiento</a>
      </div>
   </div>
 </div>

 
    

 {% endblock%}  

templates/users/match_aceptados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
      <a href="{% url 'users:UsersMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
      <a href="{% url 'users:UsersMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'users:UsersMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto ">
    <a href="{% url 'users:UsersMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'users:UsersMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
   </div>
 </div>
<div class="row">
    
    <div class="col-12 col-md-4 mx-auto py-3">
        <div class="card mb-3" style="width:100%;">
            <div class="row">
              <div class="col-md-4 p-2 mx-auto text-center">
                <img src="{% static 'images/radio_lifestyle.jpg' %}"  class="img-fluid rounded-start ">
                
              </div>
              <div class="col-md-8">
                <div class="card-body text-center">
                  <h5 class="card-title text-center bg-success text-white">{{ Nombre_Empresa }}Radio Life Style</h5>
                  <p class="card-text text-center">2019 - Actual</p>
                  <a href="#" >Mas sobre Radio Life Style</a>
                </div>
                <div class="card-footer text-muted">
                    
                    <div class="row">
                        <div class="col-12 mx-auto">
                            <p class="card-text"><small class="text-muted">Aceptado hace 2 años</small></p>
                        </div>                      
                    </div>
                  </div>
              </div>
            </div>
          </div>

    </div>
</div>

 {% endblock%}  

templates/users/match_declinados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
      <a href="{% url 'users:UsersMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
      <a href="{% url 'users:UsersMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'users:UsersMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto ">
    <a href="{% url 'users:UsersMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'users:UsersMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
   </div>
 </div>
<div class="row">
    
    <div class="col-12 col-md-4 mx-auto py-3">
        <div class="card mb-3" style="width:100%;">
            <div class="row">
              <div class="col-md-4 p-2 mx-auto text-center">
                <img src="{% static 'images/admincloud.jpg' %}"  class="img-fluid rounded-start ">
                
              </div>
              <div class="col-md-8">
                <div class="card-body text-center">
                  <h5 class="card-title text-center bg-warning">{{ Nombre_Empresa }}Admin Cloud</h5>
                  <p class="card-text text-center ">Declinado por sueldo muy bajo</p>
                  <a href="#" >Mas sobre Admin Cloud</a>
                </div>
                <div class="card-footer text-muted">
                    
                    <div class="row">
                        <div class="col-12 mx-auto">
                            <p class="card-text"><small class="text-muted">Contactado hace 2 años</small></p>
                        </div>                      
                    </div>
                  </div>
              </div>
            </div>
          </div>

    </div>
</div>


 {% endblock%}  

templates/users/match_rechazados.html
{% extends 'users/base.html' %}
 {% load static %}
 {% block title %} <span style="color: #7c9afb;">Match</span> <span style="color: #92fc69; margin-left: -10px;">Pendientes</span> {% endblock%}   
 {% block container %}
 <div class="row text-center">
  <div class="col-3 mx-auto">
      <a href="{% url 'users:UsersMatchPage' %}" class="d-lg-none btn btn-primary btn-sm" >P <span class="badge bg-secondary">1</span></a>
      <a href="{% url 'users:UsersMatchPage' %}" class="d-none d-lg-block btn btn-primary btn-sm">Pendientes <span class="badge bg-secondary">1</span></a>      
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'users:UsersMatchPageAceptados' %}" class="d-lg-none btn btn-success btn-sm" >A <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageAceptados' %}" class="d-none d-lg-block btn btn-success btn-sm">Aceptados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto ">
    <a href="{% url 'users:UsersMatchPageDeclinados' %}" class="d-lg-none btn btn-warning btn-sm" >D <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageDeclinados' %}" class="d-none d-lg-block btn btn-warning btn-sm">Declinados <span class="badge bg-secondary">1</span></a>
   </div>
   <div class="col-3 mx-auto">
    <a href="{% url 'users:UsersMatchPageRechazados' %}" class="d-lg-none btn btn-danger btn-sm" >R <span class="badge bg-secondary">1</span></a>
    <a href="{% url 'users:UsersMatchPageRechazados' %}" class="d-none d-lg-block btn btn-danger btn-sm">Rechazados <span class="badge bg-secondary">1</span></a>
   </div>
 </div>
<div class="row">
    
    <div class="col-12 col-md-4 mx-auto py-3">
        <div class="card mb-3" style="width:100%;">
            <div class="row">
              <div class="col-md-4 p-2 mx-auto text-center">
                <img src="{% static 'images/cerbero_games.png' %}"  class="img-fluid rounded-start ">
                
              </div>
              <div class="col-md-8">
                <div class="card-body text-center">
                  <h5 class="card-title text-center bg-danger text-white">{{ Nombre_Empresa }}Cerbero Games</h5>
                  <p class="card-text text-center">Se encontro otro candidato con un perfil mas adecuado para el puesto que va mas enfocado al desarrollo de videojuegos</p>
                  <a href="#" >Mas sobre Cerbero Games</a>
                </div>
                <div class="row justify-content-end text-end">
                  <div class="col-12 align-self-end offset-6">
                    <a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#ModalAceptar">¿Como conseguir puestos similares?</a>
                  </div>                      
                </div>
                <div class="card-footer text-muted">
                    
                    <div class="row">
                        <div class="col-12 mx-auto">
                            <p class="card-text"><small class="text-muted">Postulado hace 2 años</small></p>
                        </div>                      
                    </div>
                  </div>
              </div>
            </div>
          </div>

    </div>
</div>
<!-- Modal Aceptar-->
<div class="modal fade" id="ModalAceptar" tabindex="-1" aria-labelledby="ModalAceptarLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalAceptarLabel">¿Como conseguir puestos similares?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <h6>Para conseguir este puesto o similares a este te sugerimos tomar los siguientes cursos:</h6>  
          <li><a href="https://platzi.com/clases/assets-3d/" target="_blank" >Platzi: Curso de Assets 3D para Videojuegos</a></li>
          <li><a href="https://platzi.com/clases/animacion-videojuegos/" target="_blank">Platzi:  Animación y Arte de Videojuegos 2D</a></li>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
 {% endblock%}  